environment:
  matrix:
    - PYTHON: "C:\\Python27"
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe easy-install.py example/easy-install.rc"
